yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Q, F, CheckConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='comments')
    text = models.TextField()
    created = models.DateTimeField('date published', auto_now_add=True)

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following")

    class Meta:
        constraints = [models.UniqueConstraint(fields=['user', 'author'],
                       name='unique_follower'),
                       CheckConstraint(check=~Q(user=F('author')),
                       name='no_self_following')]

    def __str__(self):
        return self.text

yatube/posts/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from pytils.translit import slugify

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'group': 'Группа', 'text': 'Текст'}
        help_texts = {'text': ('Обязательное поле для заполнения')}

    def clean_slug(self):
        """Обрабатывает случай, если slug не уникален."""
        cleaned_data = super().clean()
        slug = cleaned_data.get('slug')
        if not slug:
            title = cleaned_data.get('title')
            slug = slugify(title)[:100]
        if Post.objects.filter(slug=slug).exists():
            raise ValidationError(
                f'Адрес "{slug}" уже существует, '
                'придумайте уникальное значение'
            )
        return slug


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Добавить комментарий'}
        help_texts = {'text': 'Текст комментария'}

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from posts.forms import CommentForm, PostForm
from .models import Follow, Group, Post, User


def paginate(record_set, request):
    paginator = Paginator(record_set, settings.ITEMS_COUNT)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


def index(request):
    post_list = Post.objects.all()
    context = {
        'page_obj': paginate(post_list, request),
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    context = {
        'page_obj': paginate(posts, request),
        'group': group,
        'posts': posts,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'page_obj': paginate(posts, request),
        'post_count': posts.count(),
        'author': author,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    form = CommentForm(request.POST or None)
    comments = post.comments.all()
    context = {
        'author': author,
        'post': post,
        'post_count': post.author.posts.count(),
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', username=request.user.username)

    posts_group = Group.objects.all()
    context = {
        'posts_group': posts_group,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    author = post.author
    if author != user:
        return redirect('posts:post_detail', post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    context = {'page_obj': paginate(post_list, request)}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username)

yatube/templates/posts/create_post.html
{% extends "base.html" %}

{% load user_filters %}

{% block title %}
  {% if form.instance.id %}
    Редактирование записи
  {% else %}
    Добавление записи
  {% endif %}
{% endblock %}

{% block header %}
  {% if form.instance.id %}
    Редактирование записи
  {% else %}
    Добавление записи
  {% endif %}
{% endblock %}

{% block content %}

<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if form.instance.id %}
            Редактировать запись
          {% else %}    
            Добавить запись
          {% endif %}        
        </div>
        <div class="card-body">       
          {% if form.instance.id %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_edit' form.instance.id %}">
          {% else %}
            <form method="post" enctype="multipart/form-data" action="{% url 'posts:post_create' %}">
          {% endif %}  
          {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>    
            {{ field }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if form.instance.id %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}  
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}Активные подписки{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
<main> 
  <div class="container py-5">     
    <h1>Активные подписки</h1>
    <article>
    {% for post in page_obj %}
    {% include 'includes/main.html' %}  
    {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
  </div>
{% include 'posts/includes/paginator.html' %}
</main>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Записи сообщества "{{ group }}" {% endblock %}

{% block content %}
<main>
  <div class="container py-5">
    <h1>{{ group }}</h1>
    <p>
    {{ group.description }}
    </p>
    <article>
    {% for post in posts %}
    {% include 'includes/main.html' %}
    {% endfor %}
    </article>
    {% include 'posts/includes/paginator.html' %}
  </div>   
</main>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
{% cache 20 index_page with page_obj %} 
<main> 
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
    <article>
    {% for post in page_obj %}
    {% include 'includes/main.html' %}  
    {% if post.group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы "{{ post.group.title }}"</a>
    {% endif %} 
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
  </div>
{% include 'posts/includes/paginator.html' %}
</main>
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}Пост: {{ post.text|truncatewords:30 }} {% endblock %}

{% block content %}

{% load user_filters %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      {% if post.group %}   
      <li class="list-group-item">
        Группа: {{ post.group.title }}</br>
      <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
      </li>
      <li class="list-group-item">
        Автор: {{ post.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ post_count }}      
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          все посты пользователя
        </a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text|linebreaksbr }}</p>
  </article>
  {% if user.is_authenticated and user == post.author %}
  <a href="{% url 'posts:post_edit' post.id %}" class="btn btn-link">
    Редактировать
  </a>
  {% endif %}  
</div>
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
<div style="margin-left:20px;">
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text|linebreaksbr }}
        </p>
    </div>
  </div>
{% endfor %}
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}

{% block content %}

{% load user_filters %}
<div style="margin-left:20px;">
  <div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ post_count }} </h3>
    {% if user.is_authenticated and user != author %}
      {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
      {% endif %}
    {% endif %} 
  </div>     
    <article>
      {% for post in page_obj %}
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
            <a href="{{ posts }}">все посты пользователя</a>
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }} 
          </li>
        </ul>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>{{ post.text|linebreaksbr }}</p>
        <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </br>       
      {% if post.group %}   
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}         
      <hr>
      {% endfor %}
    </article>
      {% include 'posts/includes/paginator.html' %}      
</div>
{% endblock %}